Added support for xlsx files
Molmed/clarity-ext pull request #242
Opened 2023-03-14 09:04 UTC by kleppari

- Support for reading xlsx files using openpyxl

2023-03-16 09:27 UTC, Aratz requested changes
Looks good!

My main question is regarding the `local_shared_file` function, it feels like maybe it could benefit from a rewrite.

The other main question is with the `parse_xlsx` function, I tried it locally but couldn't really make it work.

2023-03-16 09:27 UTC, Aratz commented on clarity_ext/context.py
> +    def local_shared_file(self, clarity_file_handle, mode="r", is_xml=False, is_csv=False, file_name_contains=None,
I know the body of this function is old code, but wouldn't it be better to remove the extra `is_*` arguments and only rely on detecting the file type automatically? It seems the bulk of what this function is doing is handling the case where the flag and the file type don't agree.

So I'd suggest either remove all the flags and detect the file type by looking at the extension in the file name, or, if it's important to have the user specify the file type they expect, to replace the flag args by `extension` where one could pass a string e.g. 'csv'

2023-03-16 09:27 UTC, Aratz commented on clarity_ext/context.py
> +            check_file_extension('.xlsx')
Can it happen that the extension of the sample form is just `.xls`?

2023-03-16 09:27 UTC, Aratz commented on clarity_ext/service/file_service.py
> +
I tried this locally but I get an `AttributeError: can't set attribute` when reaching `writer.book = workbook` :confused: 

Is `pd.ExcelWriter` necessary here or can you return `workbook` immediately?

2023-03-16 12:52 UTC, kleppari commented on clarity_ext/context.py
> +    def local_shared_file(self, clarity_file_handle, mode="r", is_xml=False, is_csv=False, file_name_contains=None,
I will create a ticket for this

2023-03-16 12:52 UTC, kleppari commented on clarity_ext/context.py
> +            check_file_extension('.xlsx')
No, the sample from is just .xlsx

2023-03-21 07:28 UTC, Aratz approved these changes
Looks good, although I think you need to add `openpyxl` to the requirements for the tests to pass.

2023-04-04 10:20 UTC, merged